---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    secret: AgBkXWCZNq5wjbsxK6aSKK1RcBPrbudT6cBor4WxfkCbvZbTsdkUk3grfZ8VN7RPdY5SP0/LeqoRd8CkeerITlzu5eiFXxboL/18YZdcWZPmPI19dWhknmy8tGNzUU2ACi8agP/Js266Mo8azR6e/xyU7hev/YWXTD131SL9bO5XTwESq0SrZO/gCgiYGnSCrz/ELE0PcvSRKFbiK1La5nAmjWJEgnXw+XAxR3P1rl5uA/dQzUfQKLhKVkSLtEf+qSSPHSitU+wi7P2Zgv1v9ZElmbIFu3Agble0wivHY/IWeQ/vveIUIr1ItO/BFMQqMVHxBHu3glZsgT/gv5I7+Ghnl6LqgZX7byHZnDWsi2d9vxz/Xk0oIthEKnG23zD7j7nzOXBoXS9hFVVLpq/5dlgq21d9ygixeeFnRYGHwFdUbbJYb6mJ5hCVJ0Y05QNgNqc+dQq6hNuRgo1acXupXuYoGqcl+P6foU5/pquYZrFfe9PAt9OddduLBlPnS0NM50SWdeWg/PKiu8zHOYsADBO38Av21+5890iadHjp6jCadhldm+2obUGFI2iS3bHBhXXwEr8suiBMwc7LHsMjLeo+M2qyYIiX37lWDhxNZ4GUJJBZUnFOJoKw61fXKpA+mtL3hfKR4m/kDQk/dqVIoIyWCOGU92oiR81IgJWZQSr3eEEYCOeQ41/zR/7AFz61bB4KsU5MC4D4/DwqKNQ=
  template:
    metadata:
      annotations:
        argocd.argoproj.io/show-secret-value: "true"
      creationTimestamp: null
      name: my-secret
      namespace: default
