---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    secret: AgAjlrxt2Zsi1NOs2RvNeCxtTLOBQjzXtHPHdJxfM0MhjpocZMDYrcmZOQbNdiVJ2htVvmzB2DowJYkDonxKu2LaXo/bfpzrMVZLDEzqcdRY0qbdRVcS0Ovv6vaY8H/39yRGJXg2sifWzrsmxkrcg3eUn8s3fYyePapvImUwnY5V9ylwY5CjrGJ/LuUGB9KZJUqJrykGv5SmR/+67FdnkckHIIH9HxGsijTJGKEF5tIiWQmtv49kgpKULZZbuIV1G4BWQMCcOnKt1/jXygVzeOcyIjQNwcjSHKnNH5qD0wvXdIAWrR+oCLX8OfJjvM/L1IWs/2GZuksYX2fMgQbQ8eQkRELQ8vm5zE2ntZ/s+DZrYJJMxQrx8FPk0UiaNkcANEtyYacltETGTd+uleSjIsVGNszG1W4N8XskSx0W9HXJGIAbllLjK6lsXTjiodZKgUE2JdT/6DUmPxVOGiOnSySqUs6yFsPWcB6pvO4+vQRzRViwTY6F9EU/NiwP+/iE+An9cR1SPp3SzS1fv0smJF+lgsM5bChhS1EAXmVb5E+i4M/mJUywnNOv5cp0g9xpCwEXO5wZ+acpnZlD9wRCA7mmK8fVS1K6w+VC64RJ8c6Z5pSjKhHewGiL5mKL9NVI0olmMHfCUj/AeQNURxZvJrr5NIZTPQnwVdjmK/dtKyu1MQd2dfC5eEhGgNaEIIBDcRRN5E0L2PjAH7mDvI0=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
