---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    secret: AgAEwwdYO9T2r26cXRMPXSQegck7qMneJWGRrcbLmNX9pYrILrIAzpcOdEPScFUPf7k6CR3QWETf1pBYt1pvVCh19ae1oEE+hL2jttS6J8yX33yywPr4KRQpaVVddIq6kzQmDHs3pRn2yuf2vrBFAbZzTGx5+FDNaMjxBYDxB3cRPbkVPGZLwdPVrBYXDnjJ7FCZlvzmZw6wkmOOcfx/u4QtY00Tq1SfIj6iKigBNoQrrghfKf99KU5PIf4J8PW6ONczD6a0ik1F94TcDVgJ8HgqPvoKLubczNKfKJ8/RDDg0maVmyuIVnOBSWHbXjYU6TY56ulo0bHObZWPOgCH0TzvppFoTxT59jcY29pX5co7rswPlyDlT+0SWZk5eWB2Iw69vq0DqNuejhX3d6TNHUUOqSBgjOxAiSNr2YVAkIifZl1tUGgMOWPab4+a5+D6o7tEKIGk2VGbU/LPCT56j9d+sWjQz5dWQ8odf5McJo+i/0bVROqPallXwCzemGF5illooSzr27a8QR3bk/Nks5+yOBM6O+88/o1ulrIAH3+8G2UN/Vs00ZidyMdnZY0SkUZjckyDxECqMRpjLdJR2GXcB8rD6M1h8VAxksEuXltlI1GqRmg/goHYUgOfaMeasoWLKzKqGKp21hu/2n64O/fTHiF5H3/HuI9KBtbCeEUX9rQLKY/SEM/FUUjFFSpHCf7GavCf0jWXv1Jdx7VU
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
